In [73]:
import numpy as np


In [74]:
list=[12,233,43,23]
np.array(list)

array([ 12, 233,  43,  23])

In [75]:
li=[12 ,3 ,43, 4],[1,2,3,4],[23,34,54,0]
np.array(li)

array([[12,  3, 43,  4],
       [ 1,  2,  3,  4],
       [23, 34, 54,  0]])

In [76]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [77]:
np.arange(2,61)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60])

In [78]:
np.arange(1,9,3)

array([1, 4, 7])

In [79]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
np.ones(3)

array([1., 1., 1.])

In [83]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [ ]:
np.ones(5,1)

In [ ]:
np.linspace(0,8,10)

In [ ]:
np.eye(4)

In [ ]:
np.eye(3,int)

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.randn(2,4)

In [ ]:
np.random.randint(2,10,5)

In [ ]:
ar=np.arange(2,12)
ar

In [ ]:
ar.min()

In [ ]:
ar.max()

In [ ]:
ar.argmin()

In [ ]:
ar.argmax()

In [ ]:
ar.arg(3)

In [ ]:
m=np.eye(7)

In [ ]:
m

In [ ]:
m.T

In [ ]:
ar.reshape(2,5)

#### code to import numpy
#### array of 10 zeros with int
#### 2X5 distribution 
#### 3X7 unit vector float datatypes shape
#### identity of 10x10
#### o/p:5,10,15,2,25

In [84]:
import numpy as np

In [85]:
newarr=np.zeros(10,int)
newarr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
q3=np.random.rand(2,5)
q3

array([[0.99474487, 0.45428903, 0.31276374, 0.36983755, 0.90763761],
       [0.03787629, 0.727231  , 0.47077352, 0.19904357, 0.15924887]])

In [87]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [88]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [89]:
np.linspace(5,25,5)

array([ 5., 10., 15., 20., 25.])

In [90]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [91]:
mat1=np.array(([1,6,8],[23,65,9],[987,7,75]))
mat1

array([[  1,   6,   8],
       [ 23,  65,   9],
       [987,   7,  75]])

In [92]:
mat1[1][2]

9

In [93]:
mat1[2,:]

array([987,   7,  75])

In [94]:
mat1[:,1]

array([ 6, 65,  7])

In [95]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [96]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [97]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [98]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [99]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [100]:
np.max(sample_array)

30

In [101]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [102]:
np.std(sample_array)

8.65544144839919

In [103]:
np.mean(sample_array)

15.5